#!/bin/sh

CMDS=./bin
cmd=$1

# Usage
if [ "" = "$cmd" ] ; then
  echo "Usage: modules [sub-command] <args>"
  echo
  echo "Subcommand is one of:"
  for cmd in `ls $CMDS/*sh` ; do 
    echo "* " $(grep '^#-modules' $cmd | sed -e 's/^#-//g' )
  done
  exit 0
fi

# Verify command exists
if [ ! -f "$CMDS/$cmd.sh" ] ; then
  echo "*** Unknown command: '$cmd'"
  exit 1
fi

# Run
shift
. $CMDS/common.inc
. $CMDS/$cmd.sh